[general]
###### broker config
# default broker id
id = 123
# max message size 1M
max_msg_size = 1_048_576
# local kv db path
local_db_path = "test_data/kv_db"

[network]
###### network config
ip = "127.0.0.1"
port = 9092
max_connection = 65536
#default package size 10M
max_package_size = 10_048_576
# default connection read buffer size 4kb
conn_read_buffer_size = 4096

[log]
###### general config
journal_topic_count = 2
queue_topic_count = 2
recovery_checkpoint_interval = 1000
file_records_comm_channel_size = 1000
## default 100ms
splitter_wait_interval = 100_100


###### journal config
# default segment size 1G
journal_segment_size = 1_073_741_824
journal_base_dir = "/tmp/journal"
# default index file size 10M
journal_index_file_size = 10_485_760
# default index interval 4096 bytes
journal_index_interval_bytes = 4096


###### queue config
# default segment size 1G
queue_segment_size = 1_073_741_824
queue_base_dir = "/tmp/queue"
# default index file size 10M
queue_index_file_size = 10_485_760
# default index interval 4096 bytes
queue_index_interval_bytes = 4096


[group_consume]
###### group config
group_min_session_timeout = 6_000
group_max_session_timeout = 300_000
group_initial_rebalance_delay = 3000


[active_segment_writer_pool]
# default channel capacity 1024
channel_capacity = 1024
# default num channels 4
num_channels = 2
# default monitor interval 20s
monitor_interval = 20
# default worker check timeout 200ms
worker_check_timeout = 200

[active_segment_writer]
# default buffer capacity 1M
buffer_capacity = 1_048_576
# default flush interval 500ms
flush_interval = 500


[request_handler_pool]
# default channel capacity 1024
channel_capacity = 1024
# default num channels 6
num_channels = 6
# default monitor interval 20s
monitor_interval = 20
# default worker check timeout 200ms
worker_check_timeout = 200

[partition_appender_pool]
# default partition appender channel capacity 1024
channel_capacity = 1024
# default partition appender num channels 4
num_channels = 2
# default partition appender monitor interval 20s
monitor_interval = 20
# default partition appender worker check timeout 200ms
worker_check_timeout = 200
