[general]
###### broker config
# default broker id
id = 123
# max message size 1M
max_msg_size = 1_048_576
# local kv db path
local_db_path = "test_data/kv_db"

[network]
###### network config
ip = "127.0.0.1"
port = 9092
max_connection = 65536
#default package size 10M
max_package_size = 10_048_576

[log]

###### general config
recovery_checkpoint_interval = 10
file_records_comm_channel_size = 100
## default 8192(8kb)
splitter_read_buffer_size = 8192
# default 100ms
splitter_wait_interval = 10_000


###### journal config
# default segment size 10M
journal_segment_size = 10_240
journal_base_dir = "test_data/journal"
# default index file size 10M
journal_index_file_size = 2048
# default index interval 4096 bytes
journal_index_interval_bytes = 256


###### queue config
# default segment size 10M
queue_segment_size = 10_240
queue_base_dir = "test_data/queue"
# default index file size 10M
queue_index_file_size = 2048
queue_index_interval_bytes = 256

###### kv config
kv_store_path = "test_data/kv_store/kv.db"


[group]
###### group config
group_min_session_timeout = 6_000
group_max_session_timeout = 300_000
group_initial_rebalance_delay = 3000
