[general]
###### broker config
# default broker id
id = 123
# max message size 1M
max_msg_size=1_048_576

[network]
###### network config
ip = "127.0.0.1"
port = 9092
max_connection = 65536
#default package size 10M
max_package_size = 10_048_576

[log]
###### journal config
# default segment size 10M
journal_segment_size=1_048_576
journal_base_dir="test_data/journal"
###### queue config
# default segment size 10M
queue_segment_size = 1_048_576
queue_base_dir= "test_data/queue"
###### kv config
kv_store_path = "test_data/kv_store/kv.db"
###### recovery config
recovery_checkpoint_interval=30