// Record 相关常量
pub const OFFSET_OFFSET: usize = 0;
pub const OFFSET_LENGTH: usize = 8;
pub const SIZE_OFFSET: usize = OFFSET_OFFSET + OFFSET_LENGTH;
pub const SIZE_LENGTH: usize = 4;
pub const LOG_OVERHEAD: usize = SIZE_OFFSET + SIZE_LENGTH;

pub const MAGIC_OFFSET: usize = 16;
pub const MAGIC_LENGTH: usize = 1;
pub const HEADER_SIZE_UP_TO_MAGIC: usize = MAGIC_OFFSET + MAGIC_LENGTH;

// Record Batch 相关常量
pub const BASE_OFFSET_OFFSET: i32 = 0;
pub const BASE_OFFSET_LENGTH: i32 = 8;
pub const LENGTH_OFFSET: i32 = BASE_OFFSET_OFFSET + BASE_OFFSET_LENGTH;
pub const LENGTH_LENGTH: i32 = 4;
pub const PARTITION_LEADER_EPOCH_OFFSET: i32 = LENGTH_OFFSET + LENGTH_LENGTH;
pub const PARTITION_LEADER_EPOCH_LENGTH: i32 = 4;
pub const RB_MAGIC_OFFSET: i32 = PARTITION_LEADER_EPOCH_OFFSET + PARTITION_LEADER_EPOCH_LENGTH;
pub const RB_MAGIC_LENGTH: i32 = 1;
pub const CRC_OFFSET: i32 = RB_MAGIC_OFFSET + RB_MAGIC_LENGTH;
pub const CRC_LENGTH: i32 = 4;
pub const ATTRIBUTES_OFFSET: i32 = CRC_OFFSET + CRC_LENGTH;
pub const ATTRIBUTE_LENGTH: i32 = 2;
pub const LAST_OFFSET_DELTA_OFFSET: i32 = ATTRIBUTES_OFFSET + ATTRIBUTE_LENGTH;
pub const LAST_OFFSET_DELTA_LENGTH: i32 = 4;
pub const FIRST_TIMESTAMP_OFFSET: i32 = LAST_OFFSET_DELTA_OFFSET + LAST_OFFSET_DELTA_LENGTH;
pub const FIRST_TIMESTAMP_LENGTH: i32 = 8;
pub const MAX_TIMESTAMP_OFFSET: i32 = FIRST_TIMESTAMP_OFFSET + FIRST_TIMESTAMP_LENGTH;
pub const MAX_TIMESTAMP_LENGTH: i32 = 8;
pub const PRODUCER_ID_OFFSET: i32 = MAX_TIMESTAMP_OFFSET + MAX_TIMESTAMP_LENGTH;
pub const PRODUCER_ID_LENGTH: i32 = 8;
pub const PRODUCER_EPOCH_OFFSET: i32 = PRODUCER_ID_OFFSET + PRODUCER_ID_LENGTH;
pub const PRODUCER_EPOCH_LENGTH: i32 = 2;
pub const BASE_SEQUENCE_OFFSET: i32 = PRODUCER_EPOCH_OFFSET + PRODUCER_EPOCH_LENGTH;
pub const BASE_SEQUENCE_LENGTH: i32 = 4;
pub const RECORDS_COUNT_OFFSET: i32 = BASE_SEQUENCE_OFFSET + BASE_SEQUENCE_LENGTH;
pub const RECORDS_COUNT_LENGTH: i32 = 4;
pub const RECORDS_OFFSET: i32 = RECORDS_COUNT_OFFSET + RECORDS_COUNT_LENGTH;
pub const RECORD_BATCH_OVERHEAD: i32 = RECORDS_OFFSET;

// 其他常量
pub const MAGIC: i8 = 2;
pub const NO_PRODUCER_ID: i64 = -1;
pub const NO_PRODUCER_EPOCH: i16 = -1;
pub const NO_SEQUENCE: i32 = -1;
pub const NO_PARTITION_LEADER_EPOCH: i32 = -1;
pub const ATTRIBUTES: i16 = 0;